### ISSUE TITLE
This was one of the Greatest Finds on Github for me, Not working after GV Update

### ISSUE THREAD

**Issue by jcappelmann** [DanaKowalski/AutoSMSReply#2]
I can't tell you how much I enjoyed this code when I found it.  It was working great!  I think after the recent update to Google voice, the emails include extra text, and it is not working anymore.  I have tried to add the additional text, but it still will only gives me the Menu (using your exact code) but will not reply to my response of 1 or dir.  I'm not sure if GV changed something else.  If you wanted to look at it, I would be greatly appreciative, and would be happy to paypal you a beer or coffee...

**Comment by DanaKowalski** [comment]
I got in under the one year wire! Guess I had notifications turned off, sorry. This still works, though you have to jump through hoops to authorize the gmail account to run it, it's not a trusted app etc. Sometimes the auto run gets worbled, and you have to go into g scripts and get the trigger going again.

**Comment by jcappelmann** [comment]
Very cool. Perfect timing for a new project I have.  I will try it tomorrow. Last year I could only get it to respond one time. And it didn’t matter what I sent.

**Comment by DanaKowalski** [comment]
Yeah. It will get disabled a bunch by google and now get a ton of spam. If it’s a real project, I’d recommend something like Twilio. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
